<?php
define('CNF_APPNAME','');
define('CNF_APPDESC','');
define('CNF_COMNAME','CRM SolutionWeb');
define('CNF_ADDRESS','Eros fere nostrud Facilisis luptatum occuro plaga verto');
define('CNF_TEL','+33629957457');
define('CNF_EMAIL','info@solutionweb.io');
define('CNF_FACEBOOK','https://www.facebook.com');
define('CNF_TWITTER','https://www.twitter.com/');
define('CNF_INSTAGRAM','https://www.instagram.com/');
define('CNF_TRIPADVISOR','https://www.tripadvisor.com/');
define('CNF_TAGLINE','Dont call it a dream, call it a plan');
define('CNF_TEMPCOLOR','blue');
define('CNF_API_CURRENCY','https://api.exchangeratesapi.io/latest');
define('CNF_DEF_CURRENCY','1');
define('CNF_METAKEY','');
define('CNF_METADESC','');
define('CNF_GROUP','6');
define('CNF_ACTIVATION','confirmation');
define('CNF_MAINTENANCE','');
define('CNF_SHOWHELP','ON');
define('CNF_MULTILANG','1');
define('CNF_LANG','en');
define('CNF_REGIST','true');
define('CNF_FRONT','true');
define('CNF_RECAPTCHA','false');
define('CNF_THEME','leo');
define('CNF_RECAPTCHAPUBLICKEY','');
define('CNF_RECAPTCHAPRIVATEKEY','');
define('CNF_MODE','production');
define('CNF_LOGO','logo.png');
define('CNF_HEADERIMAGE','header.jpg');
define('CNF_ALLOWIP','');
define('CNF_RESTRICIP','');
define('CNF_MAIL','phpmail');
define('CNF_DATE','M d Y');
define('CNF_APIKEY','');
define('CNF_CALENDARID','');
define('CNF_ANALYTICS','UA-XXXXX-X');
?>
